apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aki-detection-state
  namespace: oberbaum
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aki-detection
  namespace: oberbaum
spec:
  ports:
    - name: metrics  # 这里是端口的自定义名称
      port: 8440
      targetPort: 8440
      protocol: TCP
  replicas: 1
  selector:
    matchLabels:
      app: aki-detection
  template:
    metadata:
      labels:
        app: aki-detection
    spec:
      containers:
      - name: aki-detection
        image: imperialswemlsspring2024.azurecr.io/coursework4-oberbaum
        command: ["/bin/sh", "-c"]
        args:
        - >
          /model/main.py
          --history=/hospital-history/history.csv
          --MLLP_ADDRESS=$MLLP_ADDRESS
          --PAGER_ADDRESS=$PAGER_ADDRESS
        env:
        - name: MLLP_ADDRESS
          value: oberbaum-simulator.hospital:8440
        - name: PAGER_ADDRESS
          value: oberbaum-simulator.hospital:8441
        ports:
          - name: metrics
            containerPort: 8440
            protocol: TCP
        volumeMounts:
          - mountPath: "/hospital-history"
            name: hospital-history
            readOnly: true
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      initContainers:
      - name: copy-hospital-history
        image: imperialswemlsspring2024.azurecr.io/coursework4-history
        volumeMounts:
          - mountPath: "/hospital-history"
            name: hospital-history
          - mountPath: "/state"
            name: aki-detection-state
        resources:
          requests:
            memory: 1Gi
            cpu: 1
      volumes:
      - name: hospital-history
        emptyDir:
          sizeLimit: 50Mi
      - name: aki-detection-state
        persistentVolumeClaim:
          claimName: aki-detection-state