apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: aki-detection-monitor
  namespace: oberbaum
spec:
  selector:
    matchLabels:
      app: aki-detection
  namespaceSelector:
    matchNames:
    - oberbaum
  endpoints:
  - port: metrics
    path: /metrics
